# Default values for backstage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.toolchain.lead.prod.liatr.io/backstage/liatrio-backstage
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: internal-nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: true
  tls: []
  hosts:
  - host: backstage-staging.internal.lead.prod.liatr.io
    paths:
    - path: /

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi

autoscaling:
  enabled: false
  minReplicas: 1

nodeSelector: {}

tolerations: []

affinity: {}

istioDomain: ""