{{- if not (eq .Values.istioDomain "<no value>") -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
  - {{ .Chart.Name }}.{{ .Values.istioDomain }}
  gateways:
  - "istio-system/app-gateway"
  http:
  - route:
    - destination:
        host: {{ include "backstage.fullname" . }}
        port:
          number: 80
{{- end }}
